### ISSUE TITLE
Adjust Alignment for Descriptive Table of categorical variables

### ISSUE THREAD

**Issue by liud4** [fullstackstatistician/ddictR#11]
Break frequency and percentage into two columns, right align the percentage and frequencies.

**Comment by omair-a-khan** [comment]
@liud4 I have looked into making this change and then grouping the two columns under one epoch label. This is possible in my Rmd code using the kableExtra package. However, when I load this package, it renders the printing of all other data frames unreadable. I will keep investigating.
