### ISSUE TITLE
Cosmetic changes to chunk wrapper 

### ISSUE THREAD

**Issue by liud4** [fullstackstatistician/ddictR#2]
- Put Section titles on the headers of each page
- Put  "Variable: " before variable. For example, "Variable: age"
- Put "Label: " before label. For example, "Label: Age at medhx.date, recalculated"
- Change "Derivation: " to  "Description: "
- Put "Distribution: " before it plot, and move chunk_wrapper for plot right before summarize_data
- Provide Lower Unique Values and Highest Unique Values by epoch
- Update the last chunk title as "IDs of participants with missing values by Epoch: "

https://github.com/fullstackstatistician/ddictR/blob/61b64ddc47b1437806f6cb3598ccfd65ca3cecca/R/create_individual_entry.R#L1

**Comment by omair-a-khan** [comment]
running chapter header added in https://github.com/fullstackstatistician/ddictR/commit/5fb956ff8ad6d8189c41d39fbb48f84111337343 and https://github.com/fullstackstatistician/ddictR/commit/fb2ace1acdd0456a5912c5ead5821aa8519d5d32
