### ISSUE TITLE
Format for Numeric Values

### ISSUE THREAD

**Issue by liud4** [fullstackstatistician/ddictR#3]
In summarize_data, update numeric format using summary statistics across all epochs.

- Identify the smallest absolute value (denoted at v) in mean and sd, and the determine the format using log10(v).
- if v is >=10, i.e. log10(v)>=1, then no decimal places;
- if v is in [0.1, 10), i.e. log10(v) is in [-1, 1], then use format X.X;
- If v is in [0, 0.1), use the first significant digit after decimal which could be obtained using round(log10(v))+1. For example, np.executive.composite has mean of 0.007003 in Epoch 1. The first significant digit after decimal is the 3rd digit and round(log10(0.007003))+1=3

https://github.com/fullstackstatistician/ddictR/blob/61b64ddc47b1437806f6cb3598ccfd65ca3cecca/R/summarize_data.R#L20

**Comment by omair-a-khan** [comment]
The number of digits to round to will be calculated using the following code:

```
digits <- case_when(
  min.value == 0 ~ 0, # this case is explicitly specified since log10(0) is undefined
  min.value >= 10 ~ 0,
  min.value >= 0.1 ~ 1,
  min.value < 0.1 ~ floor(abs(log10(min.value))) + 1
)
```
