### ISSUE TITLE
Make sure derived variables are listed after the variables used in the derivation for Echo

### ISSUE THREAD

**Issue by liud4** [fullstackstatistician/ddictR#8]
https://github.com/fullstackstatistician/ddictR/blob/184213b9c255fc69c7a2d9c24908bd5a6ce1a8fd/variables.list.R#L112

**Comment by omair-a-khan** [comment]
This was completed by @liud4 in https://github.com/fullstackstatistician/ddictR/commit/8cdb65d7b5acfb6ddd8093f1e8d412c00f8dd45a and https://github.com/fullstackstatistician/ddictR/commit/184213b9c255fc69c7a2d9c24908bd5a6ce1a8fd. We have also asked VMAC for their input on which variables we should include and in which order. Closing.
