### ISSUE TITLE
Extract Unit from Metadata

### ISSUE THREAD

**Issue by liud4** [fullstackstatistician/ddictR#9]
Check whether the raw metadata has unit attribuite
If yes, add unit attribute to the merged rds data. For derived variables, we need to do it one by one.
Then include unit in the codebook.

**Comment by omair-a-khan** [comment]
REDCap downloaded metadata has units in "field_notes" but this column is used to store non-unit notes as well. This metadata cannot be automatically extracted at this point, but if VMAC can standardize the "field_notes" section to be solely for units, I will reopen this issue and add the appropriate code. Closing for now.
